/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "@/styles/pages/registerStyle.module.scss";
import {
  createUserWithEmailAndPassword,
  GoogleAuthProvider,
  signInWithPopup,
} from "firebase/auth";
import { auth } from "@/pages/utils/firebase";
import * as useDb from "@/pages/utils/database";
const provider = new GoogleAuthProvider();

export default function Register() {
  const [name, setName] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [usersList, setUsersList] = React.useState([]);

  React.useEffect(() => {
    useDb.getData("users", (snapshot) => {
      const data = snapshot.val();

      if (data) {
        setUsersList(data);
      }
    });
  }, []);

  // REGISTER MANUAL
  const registerManual = () => {
    createUserWithEmailAndPassword(auth, email, password)
      .then((userCredential) => {
        // Signed in
        const user = userCredential.user;

        // console.log(user);
        useDb.sendData("users", {
          ...usersList,
          [user.uid]: {
            emailVerified: user.emailVerified,
            timeStamp: new Date().getTime(),
            user_id: user.uid,
            photo: "/notfound.jpg",
            name: name,
            isOnline: false,
          },
        });
      })
      .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;
      });
  };

  // REGISTER WITH GOOGLE
  const registerGoogle = () => {
    signInWithPopup(auth, provider)
      .then((result) => {
        // The signed-in user info.
        const user = result.user;

        // console.log(result);
        useDb.sendData("users", {
          ...usersList,
          [user.uid]: {
            emailVerified: user.emailVerified,
            timeStamp: new Date().getTime(),
            user_id: user.uid,
            photo: user.photoURL,
            name: user.displayName,
            isOnline: false,
          },
        });
      })
      .catch((error) => {
        // Handle Errors here.
        const errorCode = error.code;
        const errorMessage = error.message;
        // The email of the user's account used.
        const email = error.customData.email;
        // The AuthCredential type that was used.
        const credential = GoogleAuthProvider.credentialFromError(error);
        // ...
      });
  };

  return (
    <>
      <Head>
        <title>Register | Telegram app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div
          className={`container-fluid p-0 d-flex justify-content-center align-items-center ${style.container}`}
        >
          <div className={`px-5 shadow ${style.cardRegister}`}>
            {/* TITLE */}
            <div className={`d-flex justify-content-center ${style.title}`}>
              <h4>Register</h4>
            </div>
            {/* SUB TITLE */}
            <div className={`d-block mt-3 ${style.subTitle}`}>
              <p>Let’s create your account!</p>
            </div>
            {/* FORM REGISTER */}
            <div className={`mb-4 ${style.formRegister}`}>
              <form>
                <div className="mb-3">
                  <label for="nama" class="form-label">
                    Name
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    id="nama"
                    aria-describedby="emailHelp"
                    onChange={(e) => setName(e.target.value)}
                  />
                </div>
                <div className="mb-3">
                  <label for="exampleFormControlInput1" className="form-label">
                    Email
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    id="email"
                    aria-describedby="emailHelp"
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div className="mb-3">
                  <label for="exampleFormControlInput1" className="form-label">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control"
                    id="phone"
                    aria-describedby="emailHelp"
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
              </form>
            </div>
            {/* BUTTON REGISTER */}
            <div className={`mb-3 ${style.btnRegister}`}>
              <button
                type="button"
                className="btn btn-primary rounded-pill"
                onClick={registerManual}
              >
                Register
              </button>
            </div>
            {/* REGISTER WITH GOOGLE */}
            <div className={`text-center mb-3 ${style.regWithGoogle}`}>
              <p>Register with</p>
            </div>
            {/* BUTTON GOOGLE */}
            <div className={`${style.btnGoogle}`}>
              <button
                type="button"
                className="btn btn-outline-primary rounded-pill d-flex align-items-center justify-content-center"
                onClick={registerGoogle}
              >
                <img
                  className={`me-2 ${style.iconGoogle}`}
                  src="/images/icon-google.webp"
                  alt="icon-navbar"
                />
                Google
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
